### PR TITLE
V1.2

### PR DESCRIPTION
**Pull request by daveism**
Updated the profiles url.py to account for a username with @ . -

### CODE REVIEW

**Comment by ahinz** [comment]
Hey @daveizm thanks a lot for the PR. If you have time could you rebase your changes down to one commit with a commit message similar to what you put in the pull request description?

**Comment by daveism** [comment]
Okay, I am somewhat of a GIT newbie can you give me some pointers on doing that. I looked at documentation online but it’s still kind of confusing.

**Comment by ahinz** [comment]
Git is a bit of a bear. Something like this should work:
(Note: if you've made more commits after this you might get in some hot water. If that's the case we can just take it as is)

``` bash
git rebase -i 6ad64ed52c
```

Then you'll see something like:

```
pick 256e8f0 fixed bad username resolve
pick 68b99aa fix username resolve
pick 725a925 fix username resolve

# Rebase 6ad64ed..725a925 onto 6ad64ed
#
# Commands:
#  p, pick = use commit
#  r, reword = use commit, but edit the commit message
#  e, edit = use commit, but stop for amending
#  s, squash = use commit, but meld into previous commit
#  f, fixup = like "squash", but discard this commit's log message
#  x, exec = run command (the rest of the line) using shell
#
# If you remove a line here THAT COMMIT WILL BE LOST.
# However, if you remove everything, the rebase will be aborted.
#
```

Simply change the lines to something like this:

```
pick 256e8f0 fixed bad username resolve
squash 68b99aa fix username resolve
squash 725a925 fix username resolve
```

Save the file and git will popup a new commit message window for you.

Then `git push -f origin master`

**Comment by daveism** [comment]
Is that right.

**Pull request merged**
